[project]
name = "QTR-Client"
version = "1.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Flet developer", email = "you@example.com" }
]
dependencies = [
  "flet[all]==0.28.3",
  "aiohttp",
  "mitmproxy",
  "playwright>=1.54.0",
  "certifi",
  "loguru",
  "psutil>=7.2.2",
  "requests>=2.32.5",
  "pyperclip>=1.8.2",
  "pyinstaller>=6.19.0",
  "python-barcode>=0.16.1",
  "pillow>=11.3.0",
  "pydantic>=1.10.26",
  "pywin32>=311",
  "pyftpdlib>=2.2.0",
  "httpx>=0.28.1",
  "flet-desktop>=0.28.3",
  "websockets==12.0",
  "arrow>=1.4.0",
]
dependency-groups.dev = [
    "pip",
    "watchfiles"
]

[tool.flet]
# org name in reverse domain name notation, e.g. "com.mycompany".
# Combined with project.name to build bundle ID for iOS and Android apps
org = "com.qtr"

# project display name that is used as an app title on Android and iOS home screens,
# shown in window titles and about app dialogs on desktop.
product = "QTR"

# company name to display in about app dialogs
company = "Flet"

# copyright text to display in about app dialogs
copyright = "Copyright (C) 2025 by Flet"

#compile.app = true # --compile-app
#compile.packages = true # --compile-packages
#compile.cleanup = true # --cleanup-on-compile

[tool.flet.app]
path = "src"

[tool.flet.app.boot_screen]
show = true
message = "Preparing the app for its first launch…"

[tool.flet.app.startup_screen]
show = true
message = "Starting up the app…"

[tool.flet.android]
split_per_abi = true
min_sdk_version = 21
target_sdk_version = 34

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
flet = {extras = ["all"], version = "0.28.3"}

[tool.uv]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[tool.basedpyright]

typeCheckingMode = "basic"

reportMissingImports = true
reportMissingTypeStubs = false

reportUnknownMemberType = false
reportUnknownVariableType = false

reportGeneralTypeIssues = true

[tool.ruff]
line-length = 120
target-version = "py312"
extend-exclude = ["README.md"]

[tool.ruff.lint]
select = ["C4", "E", "F", "B", "I", "PERF", "UP"]
ignore = ["PERF203","UP007","UP006","UP045", "B008"]

fixable = [
    "E",    # 基础风格
    "F",    # pyflakes
    "I",    # import排序
    "C4",   # 简化推导式
    "UP",   # pyupgrade（已排除不安全规则）
]

unfixable = [
    "B",      # bugbear（可能改语义）
    "PERF",   # 性能优化类规则（可能改逻辑）
]

[dependency-groups]
dev = [
    "pip>=26.0.1",
]
