from common.permission.model import MenuConfig
from common.permission.registry import register_menu


def _menu(
    key: str,
    name: str,
    menu_type: str,
    parent_key: str | None = None,
    *,
    perm: str = "",
    path: str = "",
    component: str = "",
    query: str = "",
    icon: str = "#",
    order: int = 1,
    is_frame: int = 1,
    is_cache: int = 0,
    visible: str = "0",
    status: str = "0",
    remark: str = "",
) -> MenuConfig:
    return MenuConfig(
        key=key,
        name=name,
        menu_type=menu_type,
        parent_key=parent_key,
        perm=perm,
        path=path,
        component=component,
        query=query,
        icon=icon,
        order=order,
        is_frame=is_frame,
        is_cache=is_cache,
        visible=visible,
        status=status,
        remark=remark,
    )


def M(
    key: str,
    name: str,
    path: str,
    icon: str,
    order: int,
    *,
    parent_key: str | None = None,
    perm: str = "",
    component: str = "",
    remark: str = "",
) -> MenuConfig:
    return _menu(
        key,
        name,
        "M",
        parent_key,
        perm=perm,
        path=path,
        component=component,
        icon=icon,
        order=order,
        remark=remark,
    )


def C(
    key: str,
    name: str,
    parent_key: str,
    path: str,
    component: str,
    perm: str,
    icon: str,
    order: int,
    *,
    remark: str = "",
) -> MenuConfig:
    return _menu(
        key,
        name,
        "C",
        parent_key,
        perm=perm,
        path=path,
        component=component,
        icon=icon,
        order=order,
        remark=remark,
    )


def F(
    key: str,
    name: str,
    parent_key: str,
    perm: str,
    order: int,
    *,
    remark: str = "",
) -> MenuConfig:
    return _menu(
        key,
        name,
        "F",
        parent_key,
        perm=perm,
        order=order,
        icon="#",
        remark=remark,
    )


MENU_DEFS: tuple[MenuConfig, ...] = (
    M("hrm.root", "测试管理", "hrm", "component", 1, remark="测试管理目录"),
    M(
        "hrm.project_manager",
        "项目管理",
        "project",
        "clipboard",
        1,
        parent_key="hrm.root",
        perm="hrm:project:list",
        component="hrm/project/index",
        remark="项目管理菜单组",
    ),
    C(
        "hrm.project",
        "项目列表",
        "hrm.project_manager",
        "project",
        "hrm/project/index",
        "hrm:project:list",
        "clipboard",
        1,
        remark="项目列表菜单",
    ),
    C(
        "hrm.debugtalk",
        "DebugTalk.py",
        "hrm.project_manager",
        "debugtalk",
        "hrm/debugtalk/index",
        "hrm:debugtalk:list",
        "code",
        2,
        remark="DebugTalk菜单",
    ),
    C(
        "hrm.module",
        "模块管理",
        "hrm.root",
        "module",
        "hrm/module/index",
        "hrm:module:list",
        "example",
        2,
        remark="模块管理菜单",
    ),
    C(
        "hrm.config",
        "配置管理",
        "hrm.root",
        "config",
        "hrm/config/index",
        "hrm:config:list",
        "system",
        3,
        remark="配置管理菜单",
    ),
    C(
        "hrm.case",
        "用例管理",
        "hrm.root",
        "case",
        "hrm/case/index",
        "hrm:case:list",
        "size",
        4,
        remark="用例管理菜单",
    ),
    M("hrm.plan", "测试计划", "qtr", "skill", 5, parent_key="hrm.root", remark="测试计划菜单组"),
    C(
        "hrm.suite",
        "测试套件",
        "hrm.plan",
        "suite",
        "qtr/suite/index",
        "qtr:suite:list",
        "swagger",
        1,
        remark="测试套件菜单",
    ),
    C(
        "hrm.job",
        "执行计划",
        "hrm.plan",
        "/qtr/job",
        "qtr/job/index",
        "qtr:job:list",
        "skill",
        2,
        remark="执行计划菜单",
    ),
    C(
        "hrm.report",
        "报告管理",
        "hrm.root",
        "report",
        "hrm/report/index",
        "hrm:report:list",
        "redis-list",
        6,
        remark="报告管理菜单",
    ),
    M("hrm.env_group", "环境管理", "hrm", "size", 7, parent_key="hrm.root", remark="环境管理菜单组"),
    C(
        "hrm.env",
        "环境管理",
        "hrm.env_group",
        "env",
        "hrm/env/index",
        "hrm:env:list",
        "textarea",
        1,
        remark="环境管理菜单",
    ),
    C(
        "hrm.agent",
        "Agent管理",
        "hrm.env_group",
        "agent",
        "hrm/agent/index",
        "qtr:agent:list",
        "druid",
        2,
        remark="Agent管理菜单",
    ),
    C(
        "hrm.forward_rules",
        "转发管理",
        "hrm.env_group",
        "forwarding",
        "hrm/forward/index",
        "qtr:forwardRules:list",
        "code",
        3,
        remark="转发管理菜单",
    ),
    C(
        "hrm.api",
        "接口管理",
        "hrm.root",
        "api",
        "hrm/api/index",
        "hrm:api:tree",
        "icon",
        8,
        remark="接口管理菜单",
    ),
    C(
        "hrm.web_case",
        "Web测试管理",
        "hrm.root",
        "webcase",
        "hrm/webcase/index",
        "hrm:webCase:list",
        "guide",
        9,
        remark="Web测试管理菜单",
    ),
    C(
        "hrm.desktop_case",
        "桌面测试管理",
        "hrm.root",
        "desktopcase",
        "hrm/desktopcase/index",
        "hrm:desktopCase:list",
        "monitor",
        10,
        remark="桌面测试管理菜单",
    ),
    C(
        "hrm.push",
        "推送配置管理",
        "hrm.root",
        "push",
        "hrm/push/index",
        "hrm:push:list",
        "message",
        11,
        remark="推送配置管理菜单",
    ),
    C(
        "hrm.mock",
        "MOCK管理",
        "hrm.root",
        "mock",
        "hrm/mock/index",
        "",
        "bug",
        12,
        remark="MOCK管理菜单",
    ),
    M("hrm.tools", "工具", "tools", "tool", 13, parent_key="hrm.root", remark="工具"),
    C(
        "hrm.json",
        "工具",
        "hrm.tools",
        "json",
        "hrm/tools/jsonParse",
        "",
        "tree-table",
        1,
        remark="json工具",
    ),
    C(
        "hrm.diff",
        "工具",
        "hrm.tools",
        "diff",
        "hrm/tools/diff",
        "",
        "tool",
        2,
        remark="diff工具",
    ),
    F("hrm.project.add", "项目新增", "hrm.project", "hrm:project:add", 1),
    F("hrm.project.edit", "项目编辑", "hrm.project", "hrm:project:edit", 2),
    F("hrm.project.remove", "项目删除", "hrm.project", "hrm:project:remove", 3),
    F("hrm.project.detail", "项目详情", "hrm.project", "hrm:project:detail", 4),
    F("hrm.debugtalk.add", "DebugTalk新增", "hrm.debugtalk", "hrm:debugtalk:add", 1),
    F("hrm.debugtalk.edit", "DebugTalk编辑", "hrm.debugtalk", "hrm:debugtalk:edit", 2),
    F("hrm.debugtalk.remove", "DebugTalk删除", "hrm.debugtalk", "hrm:debugtalk:remove", 3),
    F("hrm.debugtalk.detail", "DebugTalk详情", "hrm.debugtalk", "hrm:debugtalk:detail", 4),
    F("hrm.module.add", "模块新增", "hrm.module", "hrm:module:add", 1),
    F("hrm.module.edit", "模块编辑", "hrm.module", "hrm:module:edit", 2),
    F("hrm.module.remove", "模块删除", "hrm.module", "hrm:module:remove", 3),
    F("hrm.module.export", "模块导出", "hrm.module", "hrm:module:export", 4),
    F("hrm.module.detail", "模块详情", "hrm.module", "hrm:module:detail", 5),
    F("hrm.case.add", "用例新增", "hrm.case", "hrm:case:add", 1),
    F("hrm.case.edit", "用例编辑", "hrm.case", "hrm:case:edit", 2),
    F("hrm.case.remove", "用例删除", "hrm.case", "hrm:case:remove", 3),
    F("hrm.case.export", "用例导出", "hrm.case", "hrm:case:export", 4),
    F("hrm.case.detail", "用例详情", "hrm.case", "hrm:case:detail", 5),
    F("hrm.case.debug", "用例调试", "hrm.case", "hrm:case:debug", 6),
    F("hrm.case.run", "用例执行", "hrm.case", "hrm:case:run", 7),
    F("hrm.case.copy", "用例复制", "hrm.case", "hrm:case:copy", 8),
    F("hrm.case.history", "用例历史", "hrm.case", "hrm:case:history", 9),
    F("hrm.case.params_list", "用例参数列表", "hrm.case", "hrm:caseParams:list", 10),
    F("hrm.case.params_add", "用例参数新增", "hrm.case", "hrm:caseParams:add", 11),
    F("hrm.case.params_edit", "用例参数编辑", "hrm.case", "hrm:caseParams:edite", 12),
    F("hrm.case.params_delete", "用例参数删除", "hrm.case", "hrm:caseParams:delete", 13),
    F("hrm.case.params_import", "用例参数导入", "hrm.case", "hrm:caseParams:import", 14),
    F("hrm.case.run_history_list", "执行历史列表", "hrm.case", "hrm:history:list", 15),
    F("hrm.case.run_history_detail", "执行历史详情", "hrm.case", "hrm:history:detail", 16),
    F("hrm.case.run_history_delete", "执行历史删除", "hrm.case", "hrm:history:delete", 17),
    F("hrm.api.detail", "接口详情", "hrm.api", "hrm:api:get", 1),
    F("hrm.api.add", "接口新增", "hrm.api", "hrm:api:add", 2),
    F("hrm.api.update", "接口编辑", "hrm.api", "hrm:api:update", 3),
    F("hrm.api.delete", "接口删除", "hrm.api", "hrm:api:delete", 4),
    F("hrm.api.debug", "接口调试", "hrm.api", "hrm:api:debug", 5),
    F("hrm.api.history", "接口历史", "hrm.api", "hrm:api:history", 6),
    F("hrm.api.run_history_list", "执行历史列表", "hrm.api", "hrm:history:list", 7),
    F("hrm.api.run_history_detail", "执行历史详情", "hrm.api", "hrm:history:detail", 8),
    F("hrm.api.run_history_delete", "执行历史删除", "hrm.api", "hrm:history:delete", 9),
    F("hrm.report.detail", "报告详情", "hrm.report", "hrm:report:detail", 1),
    F("hrm.report.delete", "报告删除", "hrm.report", "hrm:report:delete", 2),
    F("hrm.report.download_html", "报告下载HTML", "hrm.report", "hrm:report:downloadHtml", 3),
    F("hrm.report.download_pdf", "报告下载PDF", "hrm.report", "hrm:report:downloadPdf", 4),
    F("hrm.env.add", "环境新增", "hrm.env", "hrm:env:add", 1),
    F("hrm.env.edit", "环境编辑", "hrm.env", "hrm:env:edit", 2),
    F("hrm.env.remove", "环境删除", "hrm.env", "hrm:env:remove", 3),
    F("hrm.env.copy", "环境复制", "hrm.env", "hrm:env:copy", 4),
    F("hrm.env.detail", "环境详情", "hrm.env", "hrm:env:detail", 5),
    F("hrm.agent.add", "Agent新增", "hrm.agent", "qtr:agent:add", 1),
    F("hrm.agent.edit", "Agent编辑", "hrm.agent", "qtr:agent:edit", 2),
    F("hrm.agent.remove", "Agent删除", "hrm.agent", "qtr:agent:remove", 3),
    F("hrm.agent.detail", "Agent详情", "hrm.agent", "qtr:agent:detail", 4),
    F("hrm.forward_rules.add", "转发规则新增", "hrm.forward_rules", "qtr:forwardRules:add", 1),
    F("hrm.forward_rules.edit", "转发规则编辑", "hrm.forward_rules", "qtr:forwardRules:edit", 2),
    F("hrm.forward_rules.remove", "转发规则删除", "hrm.forward_rules", "qtr:forwardRules:remove", 3),
    F("hrm.forward_rules.copy", "转发规则复制", "hrm.forward_rules", "qtr:forwardRules:copy", 4),
    F("hrm.forward_rules.detail", "转发规则详情", "hrm.forward_rules", "qtr:forwardRules:detail", 5),
    F("hrm.forward_rules.update", "转发规则状态修改", "hrm.forward_rules", "qtr:forwardRules:update", 6),
    F("hrm.suite.add", "测试套件新增", "hrm.suite", "qtr:suite:add", 1),
    F("hrm.suite.edit", "测试套件编辑", "hrm.suite", "qtr:suite:edit", 2),
    F("hrm.suite.config", "测试套件配置", "hrm.suite", "qtr:suite:edit", 3),
    F("hrm.suite.remove", "测试套件删除", "hrm.suite", "qtr:suite:remove", 4),
    F("hrm.suite.detail", "测试套件详情", "hrm.suite", "qtr:suite:detail", 5),
    F("hrm.job.add", "执行计划新增", "hrm.job", "qtr:job:add", 1),
    F("hrm.job.edit", "执行计划编辑", "hrm.job", "qtr:job:edit", 2),
    F("hrm.job.remove", "执行计划删除", "hrm.job", "qtr:job:remove", 3),
    F("hrm.job.export", "执行计划导出", "hrm.job", "qtr:job:export", 4),
    F("hrm.job.query", "执行计划日志", "hrm.job", "qtr:job:query", 5),
    F("hrm.job.run", "执行计划执行", "hrm.job", "qtr:job:run", 6),
    F("hrm.push.add", "推送配置新增", "hrm.push", "hrm:push:add", 1),
    F("hrm.push.edit", "推送配置编辑", "hrm.push", "hrm:push:edite", 2),
    F("hrm.push.delete", "推送配置删除", "hrm.push", "hrm:push:delete", 3),
    F("hrm.push.detail", "推送配置详情", "hrm.push", "hrm:push:detail", 4),
    F("hrm.push.all", "推送配置全部查询", "hrm.push", "hrm:push:all", 5),
    F("hrm.mock.add_rule", "Mock规则新增", "hrm.mock", "hrm:mockManager:addRule", 1),
    F("hrm.mock.copy_rule", "Mock规则复制", "hrm.mock", "hrm:mockManager:copyRule", 2),
    F("hrm.mock.edit_rule", "Mock规则编辑", "hrm.mock", "hrm:mockManager:editRule", 3),
    F("hrm.mock.remove_rule", "Mock规则删除", "hrm.mock", "hrm:mockManager:removeRule", 4),
    F("hrm.mock.detail_rule", "Mock规则详情", "hrm.mock", "hrm:mockManager:detailRule", 5),
    F("hrm.mock.export_rule", "Mock规则导出", "hrm.mock", "hrm:mockManager:exportRule", 6),
    F("hrm.mock.add_response", "Mock响应新增", "hrm.mock", "hrm:mockManager:addResponse", 7),
    F("hrm.mock.update_response", "Mock响应编辑", "hrm.mock", "hrm:mockManager:updateResponse", 8),
    F("hrm.mock.response_list", "Mock响应列表", "hrm.mock", "hrm:mockManager:responseList", 9),
    F("hrm.mock.response_detail", "Mock响应详情", "hrm.mock", "hrm:mockManager:responseDetail", 10),
    F("hrm.web_case.add", "Web用例新增", "hrm.web_case", "hrm:webCase:add", 1),
    F("hrm.web_case.edit", "Web用例编辑", "hrm.web_case", "hrm:webCase:edit", 2),
    F("hrm.web_case.remove", "Web用例删除", "hrm.web_case", "hrm:webCase:remove", 3),
    F("hrm.web_case.detail", "Web用例详情", "hrm.web_case", "hrm:webCase:detail", 4),
    F("hrm.web_case.run", "Web用例执行", "hrm.web_case", "hrm:webCase:run", 5),
    F("hrm.web_case.record", "Web用例录制", "hrm.web_case", "hrm:webCase:record", 6),
    F("hrm.web_case.history", "Web用例历史", "hrm.web_case", "hrm:webCase:history", 7),
    F("hrm.web_case.persist_context", "Web用例保留浏览器状态", "hrm.web_case", "hrm:webCase:persistContext", 8),
    F("hrm.desktop_case.add", "桌面用例新增", "hrm.desktop_case", "hrm:desktopCase:add", 1),
    F("hrm.desktop_case.edit", "桌面用例编辑", "hrm.desktop_case", "hrm:desktopCase:edit", 2),
    F("hrm.desktop_case.remove", "桌面用例删除", "hrm.desktop_case", "hrm:desktopCase:remove", 3),
    F("hrm.desktop_case.detail", "桌面用例详情", "hrm.desktop_case", "hrm:desktopCase:detail", 4),
    F("hrm.desktop_case.run", "桌面用例执行", "hrm.desktop_case", "hrm:desktopCase:run", 5),
    F("hrm.desktop_case.record", "桌面用例录制", "hrm.desktop_case", "hrm:desktopCase:record", 6),
    F("hrm.desktop_case.history", "桌面用例历史", "hrm.desktop_case", "hrm:desktopCase:history", 7),
)


def register() -> None:
    for menu in MENU_DEFS:
        register_menu(menu)
