from common.permission.model import MenuConfig
from common.permission.registry import register_menu


def _menu(
    key: str,
    name: str,
    menu_type: str,
    parent_key: str | None = None,
    *,
    perm: str = "",
    path: str = "",
    component: str = "",
    query: str = "",
    icon: str = "#",
    order: int = 1,
    is_frame: int = 1,
    is_cache: int = 0,
    visible: str = "0",
    status: str = "0",
    remark: str = "",
) -> MenuConfig:
    return MenuConfig(
        key=key,
        name=name,
        menu_type=menu_type,
        parent_key=parent_key,
        perm=perm,
        path=path,
        component=component,
        query=query,
        icon=icon,
        order=order,
        is_frame=is_frame,
        is_cache=is_cache,
        visible=visible,
        status=status,
        remark=remark,
    )


def M(
    key: str,
    name: str,
    path: str,
    icon: str,
    order: int,
    *,
    parent_key: str | None = None,
    perm: str = "",
    component: str = "",
    remark: str = "",
) -> MenuConfig:
    return _menu(
        key,
        name,
        "M",
        parent_key,
        perm=perm,
        path=path,
        component=component,
        icon=icon,
        order=order,
        remark=remark,
    )


def C(
    key: str,
    name: str,
    parent_key: str,
    path: str,
    component: str,
    perm: str,
    icon: str,
    order: int,
    *,
    remark: str = "",
) -> MenuConfig:
    return _menu(
        key,
        name,
        "C",
        parent_key,
        perm=perm,
        path=path,
        component=component,
        icon=icon,
        order=order,
        remark=remark,
    )


def F(
    key: str,
    name: str,
    parent_key: str,
    perm: str,
    order: int,
    *,
    remark: str = "",
) -> MenuConfig:
    return _menu(
        key,
        name,
        "F",
        parent_key,
        perm=perm,
        order=order,
        icon="#",
        remark=remark,
    )


MENU_DEFS: tuple[MenuConfig, ...] = (
    M("admin.system", "系统管理", "system", "system", 1, remark="系统管理目录"),
    M("admin.monitor", "系统监控", "monitor", "monitor", 2, remark="系统监控目录"),
    C(
        "admin.system.user",
        "用户管理",
        "admin.system",
        "user",
        "system/user/index",
        "system:user:list",
        "user",
        1,
        remark="用户管理菜单",
    ),
    C(
        "admin.system.role",
        "角色管理",
        "admin.system",
        "role",
        "system/role/index",
        "system:role:list",
        "peoples",
        2,
        remark="角色管理菜单",
    ),
    C(
        "admin.system.menu",
        "菜单管理",
        "admin.system",
        "menu",
        "system/menu/index",
        "system:menu:list",
        "tree-table",
        3,
        remark="菜单管理菜单",
    ),
    C(
        "admin.system.dept",
        "部门管理",
        "admin.system",
        "dept",
        "system/dept/index",
        "system:dept:list",
        "tree",
        4,
        remark="部门管理菜单",
    ),
    C(
        "admin.system.post",
        "岗位管理",
        "admin.system",
        "post",
        "system/post/index",
        "system:post:list",
        "post",
        5,
        remark="岗位管理菜单",
    ),
    C(
        "admin.system.dict",
        "字典管理",
        "admin.system",
        "dict",
        "system/dict/index",
        "system:dict:list",
        "dict",
        6,
        remark="字典管理菜单",
    ),
    C(
        "admin.system.config",
        "参数设置",
        "admin.system",
        "paramConfig",
        "system/config/index",
        "system:config:list",
        "edit",
        7,
        remark="参数设置菜单",
    ),
    C(
        "admin.system.aiprovider",
        "AI Provider管理",
        "admin.system",
        "aiprovider",
        "system/aiprovider/index",
        "system:aiprovider:list",
        "cpu",
        8,
        remark="AI Provider管理菜单",
    ),
    F(
        "admin.system.aiprovider.query",
        "AI Provider查询",
        "admin.system.aiprovider",
        "system:aiprovider:query",
        1,
        remark="AI Provider详情按钮",
    ),
    F(
        "admin.system.aiprovider.add",
        "AI Provider新增",
        "admin.system.aiprovider",
        "system:aiprovider:add",
        2,
        remark="AI Provider新增按钮",
    ),
    F(
        "admin.system.aiprovider.edit",
        "AI Provider修改",
        "admin.system.aiprovider",
        "system:aiprovider:edit",
        3,
        remark="AI Provider修改按钮",
    ),
    F(
        "admin.system.aiprovider.remove",
        "AI Provider删除",
        "admin.system.aiprovider",
        "system:aiprovider:remove",
        4,
        remark="AI Provider删除按钮",
    ),
    C(
        "admin.system.aiprompt",
        "AI提示词管理",
        "admin.system",
        "aiprompt",
        "system/aiprompt/index",
        "system:aiprompt:list",
        "edit",
        9,
        remark="AI提示词管理菜单",
    ),
    C(
        "admin.system.aiconfig",
        "AI配置中心",
        "admin.system",
        "aiconfig",
        "system/aiconfig/index",
        "system:aiconfig:list",
        "setting",
        11,
        remark="AI配置中心菜单",
    ),
    C(
        "admin.system.aitaskexecution",
        "AI执行审计",
        "admin.system",
        "aitaskexecution",
        "system/aitaskexecution/index",
        "system:aitaskexecution:list",
        "document",
        10,
        remark="AI执行审计菜单",
    ),
    C(
        "admin.system.notice",
        "通知公告",
        "admin.system",
        "notice",
        "system/notice/index",
        "system:notice:list",
        "message",
        11,
        remark="通知公告菜单",
    ),
    C(
        "admin.system.apikey",
        "API Key管理",
        "admin.system",
        "apikey",
        "system/apikey/index",
        "system:apikey:list",
        "password",
        12,
        remark="API Key管理菜单",
    ),
    M(
        "admin.system.log",
        "日志管理",
        "log",
        "log",
        9,
        parent_key="admin.system",
        remark="日志管理菜单",
    ),
    C(
        "admin.monitor.online",
        "在线用户",
        "admin.monitor",
        "online",
        "monitor/online/index",
        "monitor:online:list",
        "online",
        1,
        remark="在线用户菜单",
    ),
    C(
        "admin.monitor.job",
        "定时任务",
        "admin.monitor",
        "job",
        "monitor/job/index",
        "monitor:job:list",
        "job",
        2,
        remark="定时任务菜单",
    ),
    C(
        "admin.monitor.server",
        "服务监控",
        "admin.monitor",
        "server",
        "monitor/server/index",
        "monitor:server:list",
        "server",
        4,
        remark="服务监控菜单",
    ),
    C(
        "admin.monitor.cache",
        "缓存监控",
        "admin.monitor",
        "cache",
        "monitor/cache/index",
        "monitor:cache:list",
        "redis",
        5,
        remark="缓存监控菜单",
    ),
    C(
        "admin.monitor.cache_list",
        "缓存列表",
        "admin.monitor",
        "cacheList",
        "monitor/cache/list",
        "monitor:cache:list",
        "redis-list",
        6,
        remark="缓存列表菜单",
    ),
    C(
        "admin.system.log.operlog",
        "操作日志",
        "admin.system.log",
        "operlog",
        "monitor/operlog/index",
        "monitor:operlog:list",
        "form",
        1,
        remark="操作日志菜单",
    ),
    C(
        "admin.system.log.logininfor",
        "登录日志",
        "admin.system.log",
        "logininfor",
        "monitor/logininfor/index",
        "monitor:logininfor:list",
        "logininfor",
        2,
        remark="登录日志菜单",
    ),
    C(
        "admin.system.log.logger",
        "Logger列表",
        "admin.system.log",
        "loggerList",
        "monitor/logger/list",
        "monitor:logger:list",
        "log",
        3,
        remark="Logger列表菜单",
    ),
    F("admin.system.user.query", "用户查询", "admin.system.user", "system:user:query", 1),
    F("admin.system.user.add", "用户新增", "admin.system.user", "system:user:add", 2),
    F("admin.system.user.edit", "用户修改", "admin.system.user", "system:user:edit", 3),
    F("admin.system.user.remove", "用户删除", "admin.system.user", "system:user:remove", 4),
    F("admin.system.user.export", "用户导出", "admin.system.user", "system:user:export", 5),
    F("admin.system.user.import", "用户导入", "admin.system.user", "system:user:import", 6),
    F("admin.system.user.reset_pwd", "重置密码", "admin.system.user", "system:user:resetPwd", 7),
    F("admin.system.role.query", "角色查询", "admin.system.role", "system:role:query", 1),
    F("admin.system.role.add", "角色新增", "admin.system.role", "system:role:add", 2),
    F("admin.system.role.edit", "角色修改", "admin.system.role", "system:role:edit", 3),
    F("admin.system.role.remove", "角色删除", "admin.system.role", "system:role:remove", 4),
    F("admin.system.role.export", "角色导出", "admin.system.role", "system:role:export", 5),
    F("admin.system.menu.query", "菜单查询", "admin.system.menu", "system:menu:query", 1),
    F("admin.system.menu.add", "菜单新增", "admin.system.menu", "system:menu:add", 2),
    F("admin.system.menu.edit", "菜单修改", "admin.system.menu", "system:menu:edit", 3),
    F("admin.system.menu.remove", "菜单删除", "admin.system.menu", "system:menu:remove", 4),
    F("admin.system.dept.query", "部门查询", "admin.system.dept", "system:dept:query", 1),
    F("admin.system.dept.add", "部门新增", "admin.system.dept", "system:dept:add", 2),
    F("admin.system.dept.edit", "部门修改", "admin.system.dept", "system:dept:edit", 3),
    F("admin.system.dept.remove", "部门删除", "admin.system.dept", "system:dept:remove", 4),
    F("admin.system.post.query", "岗位查询", "admin.system.post", "system:post:query", 1),
    F("admin.system.post.add", "岗位新增", "admin.system.post", "system:post:add", 2),
    F("admin.system.post.edit", "岗位修改", "admin.system.post", "system:post:edit", 3),
    F("admin.system.post.remove", "岗位删除", "admin.system.post", "system:post:remove", 4),
    F("admin.system.post.export", "岗位导出", "admin.system.post", "system:post:export", 5),
    F("admin.system.dict.query", "字典查询", "admin.system.dict", "system:dict:query", 1),
    F("admin.system.dict.add", "字典新增", "admin.system.dict", "system:dict:add", 2),
    F("admin.system.dict.edit", "字典修改", "admin.system.dict", "system:dict:edit", 3),
    F("admin.system.dict.remove", "字典删除", "admin.system.dict", "system:dict:remove", 4),
    F("admin.system.dict.export", "字典导出", "admin.system.dict", "system:dict:export", 5),
    F("admin.system.config.query", "参数查询", "admin.system.config", "system:config:query", 1),
    F("admin.system.config.add", "参数新增", "admin.system.config", "system:config:add", 2),
    F("admin.system.config.edit", "参数修改", "admin.system.config", "system:config:edit", 3),
    F("admin.system.config.remove", "参数删除", "admin.system.config", "system:config:remove", 4),
    F("admin.system.config.export", "参数导出", "admin.system.config", "system:config:export", 5),
    F("admin.system.aiprompt.query", "AI提示词查询", "admin.system.aiprompt", "system:aiprompt:query", 1),
    F("admin.system.aiprompt.add", "AI提示词新增", "admin.system.aiprompt", "system:aiprompt:add", 2),
    F("admin.system.aiprompt.edit", "AI提示词修改", "admin.system.aiprompt", "system:aiprompt:edit", 3),
    F("admin.system.aiprompt.remove", "AI提示词删除", "admin.system.aiprompt", "system:aiprompt:remove", 4),
    F("admin.system.aiconfig.list", "AI配置查询", "admin.system.aiconfig", "system:aiconfig:list", 1),
    F("admin.system.aiconfig.edit", "AI配置修改", "admin.system.aiconfig", "system:aiconfig:edit", 2),
    F("admin.system.apikey.query", "API Key查询", "admin.system.apikey", "system:apikey:query", 1),
    F("admin.system.apikey.add", "API Key新增", "admin.system.apikey", "system:apikey:add", 2),
    F("admin.system.apikey.view", "API Key查看", "admin.system.apikey", "system:apikey:view", 3),
    F("admin.system.apikey.expire", "API Key过期", "admin.system.apikey", "system:apikey:expire", 4),
    F("admin.system.apikey.remove", "API Key删除", "admin.system.apikey", "system:apikey:remove", 5),
    F("admin.system.notice.query", "公告查询", "admin.system.notice", "system:notice:query", 1),
    F("admin.system.notice.add", "公告新增", "admin.system.notice", "system:notice:add", 2),
    F("admin.system.notice.edit", "公告修改", "admin.system.notice", "system:notice:edit", 3),
    F("admin.system.notice.remove", "公告删除", "admin.system.notice", "system:notice:remove", 4),
    F("admin.system.log.operlog.query", "操作查询", "admin.system.log.operlog", "monitor:operlog:query", 1),
    F("admin.system.log.operlog.remove", "操作删除", "admin.system.log.operlog", "monitor:operlog:remove", 2),
    F("admin.system.log.operlog.export", "日志导出", "admin.system.log.operlog", "monitor:operlog:export", 3),
    F("admin.system.log.logininfor.query", "登录查询", "admin.system.log.logininfor", "monitor:logininfor:query", 1),
    F("admin.system.log.logininfor.remove", "登录删除", "admin.system.log.logininfor", "monitor:logininfor:remove", 2),
    F("admin.system.log.logininfor.export", "日志导出", "admin.system.log.logininfor", "monitor:logininfor:export", 3),
    F("admin.system.log.logininfor.unlock", "账户解锁", "admin.system.log.logininfor", "monitor:logininfor:unlock", 4),
    F("admin.monitor.online.query", "在线查询", "admin.monitor.online", "monitor:online:query", 1),
    F("admin.monitor.online.batch_logout", "批量强退", "admin.monitor.online", "monitor:online:batchLogout", 2),
    F("admin.monitor.online.force_logout", "单条强退", "admin.monitor.online", "monitor:online:forceLogout", 3),
    F("admin.monitor.job.query", "任务查询", "admin.monitor.job", "monitor:job:query", 1),
    F("admin.monitor.job.add", "任务新增", "admin.monitor.job", "monitor:job:add", 2),
    F("admin.monitor.job.edit", "任务修改", "admin.monitor.job", "monitor:job:edit", 3),
    F("admin.monitor.job.remove", "任务删除", "admin.monitor.job", "monitor:job:remove", 4),
    F("admin.monitor.job.change_status", "状态修改", "admin.monitor.job", "monitor:job:changeStatus", 5),
    F("admin.monitor.job.export", "任务导出", "admin.monitor.job", "monitor:job:export", 6),
    F("admin.system.log.logger.level", "Logger级别调整", "admin.system.log.logger", "monitor:logger:level", 1),
)


def register() -> None:
    for menu in MENU_DEFS:
        register_menu(menu)
