"""
Agent 分发与排队配置常量。

这里集中管理 AI 分析场景的跨进程派发键名和默认值，避免在控制器、服务和任务代码中散落硬编码字符串。
"""

AGENT_AI_ANALYSIS_MAX_CONCURRENT_TASKS_CONFIG_KEY = "ticket.ai.agent.maxConcurrentTasks"
AGENT_AI_ANALYSIS_MAX_CONCURRENT_TASKS_DEFAULT = 1

AGENT_AI_ANALYSIS_QUEUE_PREFIX = "agent:ai_analysis:queue"
AGENT_AI_ANALYSIS_ACTIVE_PREFIX = "agent:ai_analysis:active"
AGENT_AI_ANALYSIS_REQUEST_PREFIX = "agent:ai_analysis:request"
AGENT_AI_ANALYSIS_STATE_PREFIX = "agent:ai_analysis:state"
AGENT_AI_ANALYSIS_RESULT_PREFIX = "agent:ai_analysis:result"
AGENT_AI_ANALYSIS_LOCK_PREFIX = "agent:ai_analysis:lock"

AGENT_AI_ANALYSIS_REQUEST_TTL_SECONDS = 24 * 60 * 60
AGENT_AI_ANALYSIS_RESULT_TTL_SECONDS = 24 * 60 * 60
AGENT_AI_ANALYSIS_LOCK_TTL_SECONDS = 5
AGENT_AI_ANALYSIS_POLL_INTERVAL_SECONDS = 0.5
AGENT_AI_ANALYSIS_ACTIVE_LEASE_BUFFER_SECONDS = 300
# 排队请求的心跳租约。等待协程会按固定间隔续租，服务重启或协程异常退出后，
# 队列头会在租约到期后被自动清理，避免旧请求长时间卡住后续分析。
AGENT_AI_ANALYSIS_QUEUED_LEASE_SECONDS = 30
AGENT_AI_ANALYSIS_QUEUED_LEASE_RENEW_INTERVAL_SECONDS = 10
AGENT_AI_ANALYSIS_WAIT_LOG_INTERVAL_SECONDS = 10
